### ISSUE TITLE
bot not working. 

### ISSUE THREAD

**Issue by Rat-S** [lorey/totally-not-jarvis#1]
i tried to use the bot, but I got the error as below:

```
$ python main.py 
  File "main.py", line 26
    def __init__(self, updater: Updater):
                              ^
SyntaxError: invalid syntax
```

Thank you.

**Comment by Rat-S** [comment]
Or: 

```
$ python3 main.py 
{'can_read_all_group_messages': True, 'username': '*_bot', 'supports_inline_queries': False, 'id': ****, 'is_bot': True, 'first_name': '**', 'can_join_groups': True}
Traceback (most recent call last):
  File "main.py", line 123, in <module>
    main()
  File "main.py", line 107, in main
    updater.job_queue.run_repeating(jarvis.events, interval, first=0)
  File "/home/pi/.local/lib/python3.7/site-packages/telegram/ext/jobqueue.py", line 301, in run_repeating
    **job_kwargs,
  File "/home/pi/.local/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 434, in add_job
    job = Job(self, **job_kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/apscheduler/job.py", line 49, in __init__
    self._modify(id=id or uuid4().hex, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/apscheduler/job.py", line 180, in _modify
    check_callable_args(func, args, kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/apscheduler/util.py", line 402, in check_callable_args
    ', '.join(unsatisfied_args))
ValueError: The following arguments have not been supplied: job

```

**Comment by lorey** [comment]
Hi @Rat-S, sorry it's not working. This is four years old now and I would not expect it to still work. Back then, it was also just a quick project. Maybe you can make use of the concepts, but this is not anywhere near stable.
